import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import RouteLoader from "@/components/RouteLoader/RouteLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
    <body>
      <Header />
      <RouteLoader />
      <main className="p-6 max-w-7xl mx-auto bg-(image:/assets/img_back.svg)">
        {children}
      </main>
    </body>
  </html>
  );
}
